services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: air
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - ia-service
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - IA_URL=${IA_URL}
      - PORT=${PORT}
      - GIN_MODE=${GIN_MODE}
    volumes:
      - ./uploads:/app/uploads
      - ./backend:/app

  db:
    image: postgres:17
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d

  ia-service:
    build:
      context: ./backend/IA
      dockerfile: Dockerfile
    ports:
      - "${IA_PORT}:${IA_PORT}"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_API_BASE=${OPENROUTER_API_BASE}
      - PORT=${PORT}
      - IA_PORT=${IA_PORT}
    volumes:
      - ./backend/IA:/app

volumes:
  postgres_data: